# Generated by Django 2.1.3 on 2019-05-26 15:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('level', models.IntegerField(null=True)),
                ('file', models.FileField(null=True, upload_to='files')),
                ('com_num', models.IntegerField(default=0)),
                ('thu_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('this_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blogs.ArticleModel')),
                ('this_c', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blogs.CommentModel')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ThumbsUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('this_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blogs.ArticleModel')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(6, '账户长度最小为6'), django.core.validators.RegexValidator('^\\w{6,11}$', '账户格式错误'), django.core.validators.MaxLengthValidator(11, '账户长度最大为11')])),
                ('password', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(6, '密码长度最小为6'), django.core.validators.MaxLengthValidator(16, '密码长度最大为16')])),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('head', models.FileField(null=True, upload_to='head', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'], '格式错误')])),
                ('sign', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^男|女{1}$', '性别输入错误')])),
                ('this_g', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blogs.Groups')),
            ],
        ),
        migrations.AddField(
            model_name='thumbsup',
            name='this_u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blogs.UserModel'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='this_u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blogs.UserModel'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='this_c',
            field=models.ManyToManyField(to='blogs.TagsModel'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='user_s',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blogs.UserModel'),
        ),
    ]
