# Generated by Django 2.1.3 on 2019-05-26 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='user_s',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.UserModel'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='this_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.ArticleModel'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='this_c',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.CommentModel'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='this_u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.UserModel'),
        ),
        migrations.AlterField(
            model_name='thumbsup',
            name='this_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.ArticleModel'),
        ),
        migrations.AlterField(
            model_name='thumbsup',
            name='this_u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.UserModel'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='this_g',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Groups'),
        ),
    ]
