# Generated by Django 2.1.3 on 2019-05-27 14:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20190526_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11, '密码长度为11位'), django.core.validators.MaxLengthValidator(11, '密码长度为11位')]),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='sex',
            field=models.CharField(max_length=2),
        ),
        migrations.AddField(
            model_name='attention',
            name='att_u1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_att', to='blogs.UserModel'),
        ),
        migrations.AddField(
            model_name='attention',
            name='att_u2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.UserModel'),
        ),
    ]
