# Generated by Django 2.1.3 on 2019-05-28 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20190527_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11, '电话号长度为11位'), django.core.validators.MaxLengthValidator(11, '电话号长度为11位')]),
        ),
    ]
