# Generated by Django 2.1.3 on 2019-05-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20190528_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='art_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='att_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='bean_num',
            field=models.IntegerField(default=0),
        ),
    ]
