# Generated by Django 2.1.3 on 2019-05-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20190528_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='this_c',
        ),
        migrations.DeleteModel(
            name='TagsModel',
        ),
    ]
