# Generated by Django 2.1.3 on 2019-05-28 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20190528_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
